### ISSUE TITLE
Web version is not playable

### ISSUE THREAD

**Issue by ghost** [Leinnan/slavic_castles#2]
Same issue I had with Opera and Chrome. 
OS: Windows 8.1

![image](https://user-images.githubusercontent.com/9692596/69732899-84635100-113d-11ea-9c98-0e3878928c19.png)

**Comment by Leinnan** [comment]
The issue is mostly related to the fact that textures does not have power-of-two dimensions. Besides that warnings game is playable?

**Comment by ghost** [comment]
I can not push button "new game", nothing happens in all three browsers. Game does not start on my computer.

**Comment by ghost** [comment]
Opera gives me another error line. But anyway -- it does not start.

![image](https://user-images.githubusercontent.com/9692596/69758462-9d392a00-1170-11ea-8efc-1f9db85f83e7.png)

**Comment by Leinnan** [comment]
Error on top isn't connected to game itself. Still- I will try to prepare special game version with logging info to browser console and ask you to check if all quicksilver events works. Because for now it looks for me that there are two possibilities:

- game doesn't detect input
- game doesnt detect collision correctly

**Comment by lenscas** [comment]
I think I can reproduce the same bug by opening the dev tools. In my case they are at the bottom of firefox and if I drag it up the game window will automatically become smaller so it stays fitting. HOWEVER the position of where you need to click seems to remain the same, at least according to the onHover effects that the buttons give.

**Comment by pickfire** [comment]
I feel like the page is getting slower and slower with more steps. Memory leak?

**Comment by lenscas** [comment]
> I feel like the page is getting slower and slower with more steps. Memory leak?

There is indeed a memory leak inside the browser build. I submitted a pull request some time ago that fixes part of it which got accepted but I don't know of that is already live and how many other places there are where this leak happens.

Luckily, native builds don't suffer this leak.

**Comment by Leinnan** [comment]
If that still happens in Bevy rewrite, there can be a new issue created.
